#- defaults:
#    link:
#      relink: true

- clean: ["~"]

- shell:
    # - git update-submodules # after linking ~/.gitconfig
    - [git submodule update --init --recursive, Installing submodules]

- link:
    ~/.config/.dotfiles:
      relink: true
      path: ""
    ~/.config/.zsh:
      relink: true
      path: "zsh"
    ~/.config/.zshrc:
      relink: true
      path: "zsh/.zshrc"
    ~/.config/.localrc:
      relink: true
      path: ".localrc"
    ~/.config/starship.toml:
      relink: true
      path: "zsh/starship.toml"
    ~/.config/.hushlogin:
      relink: true
      path: "system/.hushlogin"
    ~/.config/.editorconfig:
      relink: true
      path: "system/.editorconfig"
    ~/.config/.inputrc:
      relink: true
      path: "system/.inputrc"
    ~/.config/.gitconfig:
      relink: true
      path: "git/.gitconfig"
    ~/.config/.gitattributes:
      relink: true
      path: "git/.gitattributes"
    ~/.config/.gitignore:
      relink: true
      path: "git/.gitignore_global"
    ~/.config/vim:
      relink: true
      path: "vim"
    ~/.config/nvim:
      relink: true
      path: "nvim"
    ~/.config/nvm:
      relink: true
      path: "nvm"
    ~/.config/.vimrc:
      relink: true
      path: "vim/.vimrc"
    ~/.config/.warp:
      relink: true
      path: "warp"
    ~/.config/.cheatsheet:
      relink: true
      path: "cheatsheet"
    ~/.config/.lazygit:
      relink: true
      path: "lazygit"
    ~/projects:
      relink: true
      path: "$PROJECTS"

- shell:
    # - git update-submodules # after linking ~/.gitconfig
    - [git submodule update --init --recursive, Installing submodules]
