#- defaults:
#    link:
#      relink: true

- clean: ['~']

- shell:
  # - git update-submodules # after linking ~/.gitconfig
  - [git submodule update --init --recursive, Installing submodules]

- link:
    #~/.dotfiles:
    #    relink: true
    #    path: ''
    # ~/.bashrc:
    #     relink: true
    #     path: 'bash/bashrc'
    ~/.zshrc:
        relink: true
        path: 'zsh/zshrc'
    # ~/.bash_profile:
    #     relink: true
    #     path: 'bash/bash_profile'
    ~/.hushlogin:
        relink: true
        path: 'system/hushlogin'
    ~/.editorconfig:
        relink: true
        path: 'system/editorconfig'
    ~/.inputrc:
        relink: true
        path: 'system/inputrc'
    ~/.gitconfig:
        relink: true
        path: 'git/gitconfig'
    #~/.gitattributes:
    #    relink: true
    #    path: 'git/gitattributes'
    ~/.gitignore:
        relink: true
        path: 'git/gitignore_global'
    ~/.vim:
        relink: true
        path: 'vim'
    #~/.nvm:
    #    relink: true
    #    path: 'nvm'
    ~/.vimrc:
        relink: true
        path: 'vim/vimrc'
    ~/.warp:
        relink: true
        path: 'warp'
    ~/.cheatsheet:
        relink: true
        path: 'cheatsheet'
    ~/.config/starship.toml:
        relink: true
        path: 'zsh/starship.toml'
    # ~/projects:
    #     relink: true
    #     path: '../projects'


- shell:
  # - git update-submodules # after linking ~/.gitconfig
  - [git submodule update --init --recursive, Installing submodules]
